"""
scripts/run_forecasting.py
===========================
Pipeline dự báo doanh thu theo thời gian.
Outputs:
  - outputs/tables/forecast_metrics.csv
  - outputs/figures/forecast_plot.png
  - outputs/figures/actual_vs_pred.png
"""

import os
import sys
import warnings

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
sys.path.insert(0, ROOT)

from src.utils.config import load_config
from src.models import forecasting
from src.evaluation import metrics

warnings.filterwarnings("ignore")


def main():
    cfg = load_config(os.path.join(ROOT, "configs", "params.yaml"))
    fc_cfg = cfg.get("forecasting", {})
    date_col = fc_cfg.get("date_col", "date")
    value_col = fc_cfg.get("value_col", "revenue")
    test_periods = fc_cfg.get("test_periods", 6)
    forecast_horizon = fc_cfg.get("forecast_horizon", 12)
    arima_order = tuple(fc_cfg.get("arima_order", (1, 1, 1)))

    # load data
    # timeseries file is generated by preprocessing script and lives in processed directory
    data_path = os.path.join(ROOT, cfg["paths"]["processed_dir"], "timeseries_monthly.csv")
    df = pd.read_csv(data_path)
    # parse dates
    df[date_col] = pd.to_datetime(df[date_col])
    df = df.set_index(date_col).sort_index()
    ts = df[value_col].asfreq("MS")
    print(f"[INFO] đã tải chuỗi thời gian với {len(ts)} bản ghi")

    # split train / test chronologically
    train = ts.iloc[:-test_periods]
    test = ts.iloc[-test_periods:]

    results = []

    # naive baseline
    naive_pred = forecasting.naive_forecast(train, len(test))
    res = metrics.forecast_metrics(test, naive_pred)
    res["model"] = "naive"
    results.append(res)

    # ARIMA
    try:
        arima_model = forecasting.train_arima(train, order=arima_order)
        arima_pred = forecasting.forecast_arima(arima_model, len(test))
        res = metrics.forecast_metrics(test, arima_pred)
        res["model"] = "arima"
        results.append(res)
    except Exception as e:
        print(f"[CẢNH BÁO] ARIMA thất bại: {e}")

    # Prophet if available
    if forecasting._HAS_PROPHET:
        df_prop = train.reset_index().rename(columns={value_col: "y", date_col: "ds"})
        prop_model = forecasting.train_prophet(df_prop, date_col="ds", value_col="y")
        prop_pred = forecasting.forecast_prophet(prop_model, periods=len(test), freq="MS")
        prop_pred.index = test.index  # align
        res = metrics.forecast_metrics(test, prop_pred)
        res["model"] = "prophet"
        results.append(res)
    else:
        print("[INFO] Chưa cài Prophet; bỏ qua")

    df_results = pd.DataFrame(results).set_index("model")
    print(df_results)

    # output dirs
    output_dir = os.path.join(ROOT, cfg["paths"].get("output_dir", "outputs"))
    tables_dir = os.path.join(output_dir, "tables")
    figures_dir = os.path.join(output_dir, "figures")
    os.makedirs(tables_dir, exist_ok=True)
    os.makedirs(figures_dir, exist_ok=True)

    df_results.to_csv(os.path.join(tables_dir, "forecast_metrics.csv"))
    print(f"[LƯU] metrics")

    # plot full series vs forecasts using best model (lowest rmse)
    best = df_results["rmse"].idxmin()
    if best == "naive":
        best_pred = naive_pred
    elif best == "arima":
        best_pred = arima_pred
    elif best == "prophet":
        best_pred = prop_pred
    else:
        best_pred = pd.Series([], dtype=float)

    fig1, ax1 = plt.subplots(figsize=(10, 6))
    ts.plot(ax=ax1, label="actual")
    if not best_pred.empty:
        best_pred.plot(ax=ax1, label=f"forecast ({best})")
    ax1.set_title("Thực tế vs Dự báo")
    ax1.legend()
    plt.tight_layout()
    fig1.savefig(os.path.join(figures_dir, "forecast_plot.png"), dpi=150)
    plt.close(fig1)
    print("[LƯU] biểu đồ dự báo")

    # actual vs predicted for test window
    fig2, ax2 = plt.subplots(figsize=(8, 5))
    test.plot(ax=ax2, label="actual")
    if not best_pred.empty:
        best_pred.plot(ax=ax2, label=f"pred ({best})")
    ax2.set_title("Giai đoạn thử nghiệm: thực tế vs dự đoán")
    ax2.legend()
    plt.tight_layout()
    fig2.savefig(os.path.join(figures_dir, "actual_vs_pred.png"), dpi=150)
    plt.close(fig2)
    print("[LƯU] biểu đồ thực tế_vs_dự đoán")

    print("\n[HOÀN THÀNH] pipeline dự báo đã hoàn tất.")


if __name__ == "__main__":
    main()
